/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScriptIdRouteImport } from './routes/$scriptId'
import { Route as IndexRouteImport } from './routes/index'

const ScriptIdRoute = ScriptIdRouteImport.update({
  id: '/$scriptId',
  path: '/$scriptId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$scriptId': typeof ScriptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$scriptId': typeof ScriptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$scriptId': typeof ScriptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$scriptId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$scriptId'
  id: '__root__' | '/' | '/$scriptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScriptIdRoute: typeof ScriptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$scriptId': {
      id: '/$scriptId'
      path: '/$scriptId'
      fullPath: '/$scriptId'
      preLoaderRoute: typeof ScriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScriptIdRoute: ScriptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
